version: '2.1'

services:
  webapp:
    build:
      context: ./webapp
    ports:
      - "58080:80"

  vaddy:
    build:
      context: ./vaddy
    links:
      - webapp:www.example.jp
    #extra_host:
    #  - "www.example.jp:192.168.1.10"
